# Generated by Django 3.1.7 on 2021-09-01 16:15

from django.db import migrations
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', employee.models.UserManager()),
            ],
        ),
    ]
