# Generated by Django 3.1.7 on 2021-08-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationalID', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('experience_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=50)),
                ('little_bio', models.TextField()),
                ('views', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.city')),
                ('programming_language', models.ManyToManyField(to='employee.ProgrammingLanguage')),
            ],
        ),
    ]
