# Generated by Django 3.1.7 on 2021-08-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='programming_language',
            field=models.ManyToManyField(to='employee.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.experiencelevel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.experiencelevel'),
        ),
    ]
