# Generated by Django 3.1.7 on 2021-08-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ManyToManyField(to='employee.City'),
        ),
    ]
