# Generated by Django 3.1.7 on 2021-10-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210904_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
