# Generated by Django 3.1.7 on 2021-08-20 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0006_auto_20210820_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.city'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.experiencelevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
