# Generated by Django 3.1.7 on 2021-08-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0010_auto_20210823_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationalID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
