# Generated by Django 3.1.7 on 2021-08-23 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0012_auto_20210823_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[(0, 'Open'), (1, 'Closed')], default='Open', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience_level',
            field=models.CharField(choices=[('Jr', 'Junior'), ('Mid', 'Mid'), ('Sr', 'Senior')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationalID',
            field=models.CharField(error_messages={'invalid': 'National Id is already exist!'}, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(default='Cairo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='Desc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Jr', 'Junior'), ('Mid', 'Mid'), ('Sr', 'Senior')], default='Jr', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_status', models.CharField(choices=[(0, 'Review'), (1, 'Accepted'), (2, 'Rejected')], max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.job')),
            ],
        ),
    ]
