# Generated by Django 3.1.7 on 2021-08-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20210823_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant_status',
            field=models.CharField(choices=[(0, 'Review'), (1, 'Accepted'), (2, 'Rejected')], default='Review', max_length=50),
        ),
    ]
