# Generated by Django 3.1.7 on 2021-08-23 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20210823_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
