# Generated by Django 3.1.7 on 2021-08-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20210823_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationalID',
            field=models.CharField(error_messages={'invalid': 'National Id is already exist!'}, max_length=14, primary_key=True, serialize=False),
        ),
    ]
