# Generated by Django 3.1.7 on 2021-08-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_remove_employee_views'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='employee',
            name='nationalID',
            field=models.CharField(error_messages={'invalid': 'National Id is already exist!'}, max_length=14, unique=True),
        ),
    ]
