# Generated by Django 3.1.7 on 2021-08-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20210824_0129'),
        ('employee', '0019_auto_20210824_0136'),
    ]

    operations = [
    ]
