# Generated by Django 3.1.7 on 2021-08-24 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0024_auto_20210824_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')]),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant_status',
            field=models.IntegerField(choices=[(0, 'Review'), (1, 'Accepted'), (2, 'Rejected')], default='Review'),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
