# Generated by Django 3.1.7 on 2021-08-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20210824_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
