# Generated by Django 3.1.7 on 2021-08-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employee_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
