# Generated by Django 3.1.7 on 2021-08-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_programminglanguage_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Jr'), ('Mid', 'Mid'), ('Senior', 'Sr')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Jr'), ('Mid', 'Mid'), ('Senior', 'Sr')], max_length=50),
        ),
    ]
