# Generated by Django 3.1.7 on 2021-08-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_auto_20210825_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
