# Generated by Django 3.1.7 on 2021-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant_status',
            field=models.CharField(choices=[(0, 'Review'), (1, 'Accepted'), (2, 'Rejected')], default='Review', max_length=50),
        ),
    ]
