# Generated by Django 3.1.7 on 2021-08-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_auto_20210826_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='employer',
        ),
    ]
